workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    
    integrations:
      app_store_connect: Saman Marketpalce
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.saeed.saman
      
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        APP_ID: 6744526430
      
      node: 20
      xcode: latest
      cocoapods: default
    
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true
    
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      
      - name: Build web app
        script: |
          npm run build
      
      - name: Add iOS platform
        script: |
          npx cap add ios || true
      
      - name: Capacitor sync
        script: |
          npx cap sync ios
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install
      
      - name: Set up code signing
        script: |
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles
      
      - name: Set version and build number
        script: |
          cd $CM_BUILD_DIR/ios/App
          # Set version to 2.0.1 (higher than previous 2.0.0)
          agvtool new-marketing-version 2.0.1
          # Get latest build number from App Store Connect and increment
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-build-number "$APP_ID" --platform IOS 2>/dev/null || echo "20")
          NEW_BUILD=$((LATEST_BUILD_NUMBER + 1))
          # Ensure build number is higher than any previously used
          if [ $NEW_BUILD -lt 90 ]; then NEW_BUILD=90; fi
          echo "Setting build number to $NEW_BUILD"
          agvtool new-version -all $NEW_BUILD
      
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
      
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      vars:
        PACKAGE_NAME: "com.saeed.saman"
      java: 21
      node: 20
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      
      - name: Build web app
        script: |
          npm run build
      
      - name: Add Android platform
        script: |
          npx cap add android || true
      
      - name: Capacitor sync
        script: |
          npx cap sync android
      
      - name: Set up signing keystore
        script: |
          # Use the upload keystore included in the repo
          cat > $CM_BUILD_DIR/android/key.properties <<EOF
          storePassword=saman2024
          keyPassword=saman2024
          keyAlias=upload
          storeFile=$CM_BUILD_DIR/android/app/upload-key.keystore
          EOF
      
      - name: Build Android Release AAB
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease
    
    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk
    
    publishing:
      email:
        recipients:
          - saeed.hokal@hotmail.com
        notify:
          success: true
          failure: true
